- name: Credentials Example
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    dnac_host: <IP/FQDN>
    dnac_username: <username>
    dnac_password: <password>
    dnac_verify: False
    dnac_port: 443
    dnac_version: 2.2.2.3
    dnac_debug: False

  tasks:
  - name: Create SNMPv3 Credentials
    cisco.dnac.snmpv3_credential:
      dnac_host: "{{dnac_host}}"
      dnac_username: "{{dnac_username}}"
      dnac_password: "{{dnac_password}}"
      dnac_verify: "{{dnac_verify}}"
      dnac_port: "{{dnac_port}}"
      dnac_version: "{{dnac_version}}"
      dnac_debug: "{{dnac_debug}}"
      authType: "SHA"
      authPassword: "DNAC-2020"
      snmpMode: "AUTHPRIV"
      username: "dnac-guide"
      privacyType: "AES128"
      privacyPassword: "DNAC-PRIV-2020"
      description: "DNAC Guide"
      state: present

  - name: Create SNMPv3 Credentials - 2
    cisco.dnac.snmpv3_credential:
      dnac_host: "{{dnac_host}}"
      dnac_username: "{{dnac_username}}"
      dnac_password: "{{dnac_password}}"
      dnac_verify: "{{dnac_verify}}"
      dnac_port: "{{dnac_port}}"
      dnac_version: "{{dnac_version}}"
      dnac_debug: "{{dnac_debug}}"
      snmpMode: "NOAUTHNOPRIV"
      username: "dnac-guide-2"
      description: "DNAC Guide 2"
      state: present

  - name: Get SNMPv3 Credentials
    cisco.dnac.global_credential_info:
      dnac_host: "{{dnac_host}}"
      dnac_username: "{{dnac_username}}"
      dnac_password: "{{dnac_password}}"
      dnac_verify: "{{dnac_verify}}"
      dnac_port: "{{dnac_port}}"
      dnac_version: "{{dnac_version}}"
      dnac_debug: "{{dnac_debug}}"
      credentialSubType: "SNMPV3"
    register: snmpv3_credentials

  - name: Print SNMPv3 Credentials
    ansible.builtin.debug:
      var: snmpv3_credentials

  - name: Create HTTP Write Credentials
    cisco.dnac.http_write_credential:
      dnac_host: "{{dnac_host}}"
      dnac_username: "{{dnac_username}}"
      dnac_password: "{{dnac_password}}"
      dnac_verify: "{{dnac_verify}}"
      dnac_port: "{{dnac_port}}"
      dnac_version: "{{dnac_version}}"
      dnac_debug: "{{dnac_debug}}"
      description: "DNAC Guide"
      password: "HTTP-cr3d$"
      port: 443
      secure: true
      username: "dna-http-user"
      state: present

  - name: Get HTTP Write Credentials
    cisco.dnac.global_credential_info:
      dnac_host: "{{dnac_host}}"
      dnac_username: "{{dnac_username}}"
      dnac_password: "{{dnac_password}}"
      dnac_verify: "{{dnac_verify}}"
      dnac_port: "{{dnac_port}}"
      dnac_version: "{{dnac_version}}"
      dnac_debug: "{{dnac_debug}}"
      credentialSubType: "HTTP_WRITE"
    register: http_write_credentials

  - name: Print HTTP Write Credentials
    ansible.builtin.debug:
      var: http_write_credentials

  - name: Create CLI Credentials
    cisco.dnac.cli_credential:
      dnac_host: "{{dnac_host}}"
      dnac_username: "{{dnac_username}}"
      dnac_password: "{{dnac_password}}"
      dnac_verify: "{{dnac_verify}}"
      dnac_port: "{{dnac_port}}"
      dnac_version: "{{dnac_version}}"
      dnac_debug: "{{dnac_debug}}"
      description: "DNAC Guide"
      enablePassword: "Cisco123!"
      password: "Cisco123!"
      username: "dnac"
      state: present

  - name: Get CLI Credentials
    cisco.dnac.global_credential_info:
      dnac_host: "{{dnac_host}}"
      dnac_username: "{{dnac_username}}"
      dnac_password: "{{dnac_password}}"
      dnac_verify: "{{dnac_verify}}"
      dnac_port: "{{dnac_port}}"
      dnac_version: "{{dnac_version}}"
      dnac_debug: "{{dnac_debug}}"
      credentialSubType: "CLI"
    register: cli_credentials

  - name: Print CLI Credentials
    ansible.builtin.debug:
      var: cli_credentials
